In [1]:
import pandas as pd

In [2]:
df= pd.read_csv('nepse.csv')

In [3]:
df

,Symbol,Date,Open,High,Low,Close,Percent Change,Volume,Turn Over
0,NEPSE,2026-03-30,2881.98,2891.53,2821.82,2831.39,-1.65 %,"12,966,659,168.04",-
1,NEPSE,2026-03-29,2958.78,2958.79,2872.99,2879.11,-2.40 %,"15,033,310,867.98",-
2,NEPSE,2026-03-26,2933.89,2951.18,2918.36,2950.50,0.49 %,"13,148,511,094.97",-
3,NEPSE,2026-03-25,2964.68,2969.50,2929.44,2935.94,-0.82 %,"15,090,416,846.15",-
4,NEPSE,2026-03-24,2943.47,2960.40,2928.34,2960.40,0.81 %,"14,839,183,643.29",-
...,...,...,...,...,...,...,...,...,...
1152,NEPSE,2021-04-06,2678.96,2678.96,2641.80,2674.47,0.00 %,"7,477,795,737.92",-
1153,NEPSE,2021-04-05,2679.39,2682.27,2639.67,2658.75,0.00 %,"7,296,760,155.82",-
1154,NEPSE,2021-04-04,2658.31,2658.73,2646.05,2657.61,0.00 %,"9,006,858,557.96",-
1155,NEPSE,2021-04-01,2645.50,2645.50,2615.26,2631.90,0.00 %,"7,250,924,123.60",-
1156,NEPSE,2021-03-31,2596.66,2619.15,2592.80,2619.03,0.00 %,"6,166,900,815.53",-

In [4]:
df= df[['Symbol','Date', 'Open', 'High', 'Low', 'Close', 'Volume']]

In [5]:
df

     Symbol        Date     Open     High      Low    Close             Volume
0     NEPSE  2026-03-30  2881.98  2891.53  2821.82  2831.39  12,966,659,168.04
1     NEPSE  2026-03-29  2958.78  2958.79  2872.99  2879.11  15,033,310,867.98
2     NEPSE  2026-03-26  2933.89  2951.18  2918.36  2950.50  13,148,511,094.97
3     NEPSE  2026-03-25  2964.68  2969.50  2929.44  2935.94  15,090,416,846.15
4     NEPSE  2026-03-24  2943.47  2960.40  2928.34  2960.40  14,839,183,643.29
...     ...         ...      ...      ...      ...      ...                ...
1152  NEPSE  2021-04-06  2678.96  2678.96  2641.80  2674.47   7,477,795,737.92
1153  NEPSE  2021-04-05  2679.39  2682.27  2639.67  2658.75   7,296,760,155.82
1154  NEPSE  2021-04-04  2658.31  2658.73  2646.05  2657.61   9,006,858,557.96
1155  NEPSE  2021-04-01  2645.50  2645.50  2615.26  2631.90   7,250,924,123.60
1156  NEPSE  2021-03-31  2596.66  2619.15  2592.80  2619.03   6,166,900,815.53

[1157 rows x 7 columns]